//==========================================================================
//  Shadow Force -- where each ROM region lives in SDRAM
//
//  GENERATED by tools/build_rom.py --svh.  Do not edit: REGIONS in
//  that script is the single source of truth for the .mra, the
//  download image and this header.  If they disagree the core loads
//  real ROM data at the wrong addresses and every symptom looks
//  like a decode bug.
//
//      region      byte base      size       word base
//      maincpu    0x0000000     1024 K   0x0000000
//      audiocpu   0x0100000       64 K   0x0080000
//      chars      0x0110000      128 K   0x0088000
//      tiles      0x0130000     3072 K   0x0098000
//      sprites    0x0430000    10240 K   0x0218000
//      oki        0x0E30000      512 K   0x0718000
//      total      0x0EB0000    15040 K
//
//  SDRAM is addressed in 16-bit words and the download image is
//  bytes, so every word base is the byte base / 2.  Word W holds
//  byte 2W in bits [15:8] and byte 2W+1 in [7:0] -- big-endian,
//  which is what the 68000 wants.
//==========================================================================

localparam [24:0] MAINCPU_BASE_W = 25'h000000;
localparam [24:0] AUDIOCPU_BASE_W = 25'h080000;
localparam [24:0] CHARS_BASE_W = 25'h088000;
localparam [24:0] TILES_BASE_W = 25'h098000;
localparam [24:0] SPRITES_BASE_W = 25'h218000;
localparam [24:0] OKI_BASE_W = 25'h718000;

localparam [24:0] ROM_TOTAL_W = 25'h758000;
